name: RunChecks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          go-version: [ '1.23' ]
    steps:
      - actions/checkout@v4
      - name: Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: |
          go vet ./...
          go build -v ./...
          

          
        
